// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJN_4AJPNuPo69bLGHBM4eo3p_8xRVRBY',
    appId: '1:171510184064:web:8107f4731571f2a2314e65',
    messagingSenderId: '171510184064',
    projectId: 'introspecks-60108',
    authDomain: 'introspecks-60108.firebaseapp.com',
    storageBucket: 'introspecks-60108.firebasestorage.app',
    measurementId: 'G-WR6G5XS6RY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcxyb_23oCo-JfQqAiYD6guhfC9h2NnJw',
    appId: '1:171510184064:android:6f9f277b6f8e95d4314e65',
    messagingSenderId: '171510184064',
    projectId: 'introspecks-60108',
    storageBucket: 'introspecks-60108.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi0aODIbef4kssIJuSrRoWsshlyPYTeU0',
    appId: '1:171510184064:ios:45b752c53f48e477314e65',
    messagingSenderId: '171510184064',
    projectId: 'introspecks-60108',
    storageBucket: 'introspecks-60108.firebasestorage.app',
    iosBundleId: 'com.example.myDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi0aODIbef4kssIJuSrRoWsshlyPYTeU0',
    appId: '1:171510184064:ios:45b752c53f48e477314e65',
    messagingSenderId: '171510184064',
    projectId: 'introspecks-60108',
    storageBucket: 'introspecks-60108.firebasestorage.app',
    iosBundleId: 'com.example.myDiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJN_4AJPNuPo69bLGHBM4eo3p_8xRVRBY',
    appId: '1:171510184064:web:aae2673a28282a2c314e65',
    messagingSenderId: '171510184064',
    projectId: 'introspecks-60108',
    authDomain: 'introspecks-60108.firebaseapp.com',
    storageBucket: 'introspecks-60108.firebasestorage.app',
    measurementId: 'G-GHGST4PRL5',
  );
}
